#!/bin/bash

command=$1
shift

DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

. $DIR/../benchmarks/folder.cfg

AR=$BINUTILS_BUILD_DIR/binutils/ar
GOLD_PLUGIN=$LLVM_BUILD_DIR/../lib/LLVMgold.so

>&2 echo "AR: $AR ${command} --plugin $GOLD_PLUGIN $*"

$AR $command --plugin $GOLD_PLUGIN $*
